name: my-workflow
on: 
  workflow_dispatch:
    inputs:
      name:
        description: 'name of the person'
        required: true
        default: 'Meiner'
      country:
        description: 'country'
        required: true
jobs:
  greetuser:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hi ${{ github.event.inputs.name }}!"
          echo "- in ${{ github.event.inputs.country }}!"
